name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Run unit tests
        run: npm run test:unit -- --ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright suite
        run: npm run test:e2e -- --reporter=dot

      - name: Build bundle (enforces size budget)
        run: npm run build

      - name: Lighthouse performance budget
        run: npm run test:perf
        env:
          CI: true
